#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Sets up the PA VM on the devbox (#27, #30): the steps only the owner can do, and the deploy
# scripts for the rest. Every stage checks its result, and re-running skips what's done.
# Run it on the devbox: deploy/home/setup-wizard.sh

source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

TOTAL_STAGES=14

# run CMD... shows a command, then runs it; a failure stops the wizard.
run() {
  printf '  %s$ %s%s\n' "$DIM" "$*" "$RESET"
  "$@" || { printf '  %s✗ failed:%s %s\n' "$RED" "$RESET" "$*"; exit 1; }
}
ok() { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }

# vm_tagged: the VM is on the tailnet as tag:pa.
vm_tagged() { incus exec "$PA_VM" -- tailscale status --json 2>/dev/null | grep -q '"tag:pa"'; }

# claude_logged_in: Claude Code in the VM is logged in, as the assistant user.
claude_logged_in() {
  incus exec "$PA_VM" -- runuser -l "$PA_USER" -c '.local/bin/claude auth status' 2>/dev/null |
    grep -q '"loggedIn": true'
}

banner "PA VM setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Remove the LXD snap"
say "LXD was installed by accident (Ubuntu's lxd shim installs it silently). It has no"
say "instances, but it would compete with Incus for bridges and DNS, so it goes, and so"
say "does the lxd-installer shim, so it can't come back."
lxd_snap() { snap list lxd >/dev/null 2>&1; }
lxd_shim() { dpkg-query -W -f='${Status}' lxd-installer 2>/dev/null | grep -q 'install ok installed'; }
if lxd_snap || lxd_shim; then
  if confirm "Remove the LXD snap and the lxd-installer package?"; then
    lxd_snap && run sudo snap remove --purge lxd
    lxd_shim && run sudo apt-get remove -y lxd-installer
  else
    SKIPPED+=("removing the LXD snap (re-run the wizard)")
  fi
fi
if ! lxd_snap && ! lxd_shim; then ok "LXD is gone"; else warn "LXD is still installed"; fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Repair apt and install Incus"
cuda_list=/etc/apt/sources.list.d/cuda-ubuntu2604-x86_64.list
if ! sudo apt-get update; then
  warn "apt update failed. If the errors above name the NVIDIA CUDA list, setting that list"
  warn "aside lets apt work (rename it back to re-enable CUDA updates)."
  if [[ -f $cuda_list ]] && confirm "Rename $cuda_list to .disabled and retry?"; then
    run sudo mv "$cuda_list" "$cuda_list.disabled"
    run sudo apt-get update
  else
    printf '  %s✗ apt is still broken; fix it and re-run the wizard%s\n' "$RED" "$RESET"; exit 1
  fi
fi
ok "apt update works"
run sudo apt-get install -y incus btrfs-progs
run sudo usermod -aG incus-admin "$USER"
note "You're in incus-admin from your next login; until then the scripts use sudo."
# shellcheck disable=SC2033 # the binary, not lib.sh's wrapper
run sudo incus info >/dev/null
ok "Incus is running"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Incus storage and bridge"
say "A btrfs storage pool (snapshots are cheap) and the VM's own bridge, $PA_BRIDGE, IPv4 only."
run "$DEPLOY_DIR/incus-setup.sh"
ok "pool $PA_POOL and bridge $PA_BRIDGE are ready"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Firewall on the VM's bridge"
say "Drops everything from the VM to private and tailnet ranges and to the devbox itself,"
say "except DNS and DHCP. Loads at every boot, before Incus; if it fails, the VM stays down."
run "$DEPLOY_DIR/install-firewall.sh"
systemctl is-enabled --quiet pa-vm-firewall.service && ok "pa-vm-firewall.service is enabled"
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Create the VM"
say "Ubuntu 26.04, 4 vCPU, 6 GiB RAM, 40 GiB disk, user $PA_USER, Tailscale installed."
note "The first run downloads the image and waits for cloud-init: a few minutes."
run "$DEPLOY_DIR/create-vm.sh"
ok "$PA_VM is running"
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Seed the instance's data root"
say "The store stays on the devbox, at $PA_DATA_ROOT. For v0.11 it holds the synthetic"
say "corpus, with its fictional owner as the instance owner; v0.13 starts a fresh one."
run "$DEPLOY_DIR/seed-data-root.sh"
ok "$(find "$PA_DATA_ROOT/l0/episodes" -name '*.json' | wc -l) episodes in L0"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Mount the store into the VM"
say "L0 goes in read-only at $PA_VM_L0, enforced on the devbox so even root in the VM can't"
say "write it. inbox/assistant_chat/ goes in writable at $PA_VM_CHAT_INBOX: the VM's only"
say "way back. Nothing else of the data root goes in."
run "$DEPLOY_DIR/mount-store.sh"
ok "the store is mounted"
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Deploy the repo into the VM"
say "Snapshots the VM, installs uv and Claude Code, clones the public repo at a ref and"
say "runs uv sync, then renders the agent project into $PA_VM_PROJECT. The ref must be"
say "pushed to GitHub."
upstream=$(git -C "$DEPLOY_DIR" rev-parse --abbrev-ref '@{upstream}' 2>/dev/null || true)
default_ref=${upstream#origin/}; default_ref=${default_ref:-main}
printf '  %sRef to deploy%s %s[Enter for %s]%s ' "$BOLD" "$RESET" "$DIM" "$default_ref" "$RESET"
read -r ref || true
run "$DEPLOY_DIR/update.sh" "${ref:-$default_ref}"
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Log the VM in to Claude"
if claude_logged_in; then
  ok "Claude Code in $PA_VM is already logged in"
else
  say "Claude Code in the VM runs on your Claude subscription, for evals and for chat."
  step "Claude prints a URL below. Open it and sign in with your Claude account."
  step "Paste the code it gives you back here."
  note "Use claude auth login, not setup-token: Remote Control refuses setup tokens."
  printf '\n'
  run incus exec -t "$PA_VM" -- runuser -l "$PA_USER" -c '.local/bin/claude auth login'
  claude_logged_in || { printf '  %s✗ Claude Code in %s isn'"'"'t logged in%s\n' "$RED" "$PA_VM" "$RESET"; exit 1; }
  ok "Claude Code in $PA_VM is logged in"
fi
pause

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Tailnet policy"
say "The VM will join as tag:pa. The policy must let your devices reach it and each other,"
say "and let tag:pa reach nothing."
if vm_tagged; then
  ok "$PA_VM is already on the tailnet as tag:pa; skipping"
else
  open_url "https://login.tailscale.com/admin/acls/file"
  step "In the policy file, merge in the three parts shown below:"
  step "tagOwners: add tag:pa, owned by autogroup:admin."
  step "grants: delete any rule whose src is \"*\" (the default allow-all is one), and add"
  step "  the two grants: your devices to autogroup:self, and your devices to tag:pa."
  step "ssh: add the rule letting your devices in to tag:pa as user assistant. Keep your"
  step "  existing ssh rules."
  step "Save. The console rejects a policy that doesn't parse."
  printf '\n'
  sed 's/^/    /' "$DEPLOY_DIR/tailscale-policy.hujson"
  printf '\n'
  pause "Press Enter once the policy is saved"
fi

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Join the VM to the tailnet as tag:pa"
if vm_tagged; then
  ok "$PA_VM is already on the tailnet as tag:pa"
else
  say "The VM asks to join; Tailscale prints a login URL below."
  step "Open the URL, log in as yourself (you own tag:pa, so the VM joins tagged)."
  step "The command returns once you've approved it."
  printf '\n'
  run incus exec "$PA_VM" -- tailscale up --advertise-tags=tag:pa --ssh --hostname="$PA_VM"
  vm_tagged || { printf '  %s✗ %s isn'"'"'t tagged tag:pa%s\n' "$RED" "$PA_VM" "$RESET"; exit 1; }
  ok "$PA_VM joined as tag:pa"
fi
note "Tagged devices don't expire; the VM reconnects on its own after reboots."
pause

# ── 12 ────────────────────────────────────────────────────────────────────
stage "Check your devices"
say "Your devices still reach each other (from the devbox):"
while read -r ip host; do
  if ping -c1 -W2 "$ip" >/dev/null 2>&1; then ok "$host ($ip)"; else warn "$host ($ip) doesn't answer (asleep?)"; fi
done < <(tailscale status | awk -v vm="$PA_VM" '$1 ~ /^100\./ && $2 != vm && !/offline/ {print $1, $2}')
printf '\n'
say "Now from the Mac:"
step "ssh $PA_USER@$PA_VM   (expect a prompt $PA_USER@$PA_VM; then exit)"
step "ssh devbox            (your devices still reach the devbox)"
if confirm "Did both work?"; then
  ok "SSH over Tailscale works"
else
  SKIPPED+=("SSH from the Mac: check the tailnet policy (stage 7) and re-run")
fi
pause

# ── 13 ────────────────────────────────────────────────────────────────────
stage "Isolation check"
say "From inside the VM: the devbox, its Docker services, the LAN and tailnet peers must be"
say "unreachable, and the internet and Anthropic's API reachable."
printf '\n'
if "$DEPLOY_DIR/check-isolation.sh"; then
  ok "every fence holds"
else
  SKIPPED+=("isolation check failed: fix and re-run deploy/home/check-isolation.sh")
fi
pause

# ── 14 ────────────────────────────────────────────────────────────────────
stage "Store check"
say "From inside the VM: L0 is readable where the agent project says, and unwritable even as"
say "root; inbox/assistant_chat/ is writable; nothing else of the data root is visible."
printf '\n'
if "$DEPLOY_DIR/check-store.sh"; then
  ok "the store's mounts hold"
else
  SKIPPED+=("store check failed: fix and re-run deploy/home/check-store.sh")
fi
pause

finish
note "Still to prove for #27's acceptance run (see deploy/home/README.md):"
note "  - reboot the devbox, then re-run deploy/home/check-isolation.sh"
note "  - roll back: deploy/home/update.sh <ref>, change something, deploy/home/rollback.sh"
note "And for #30's: deploy/home/run-evals.sh runs the eval set in the VM."
printf '\n'
